In [1]:
import numpy as np

In [5]:
#1. Write a NumPy program to create an array with the values 1, 7, 13, 105    and determine the size of the memory occupied by the array.
arr = np.array([1,7,13,105])
print(f"arr = {arr}")
print(f"total elements in arr = {arr.size}")
print(f"memory = {arr.nbytes}")

arr = [  1   7  13 105]
total elements in arr = 4
memory = 32


In [78]:
#2. Write a NumPy program to create an element-wise comparison (greater,    greater_equal, less and less_equal) of two given arrays.
def index(i):
    arr1 = np.array([10,22,30,40,65,34,54])
    arr2 = np.array([11,22,23,44,56,34,54])
    print(arr1)
    print(arr2)
    if arr1[i]==arr2[i]:
        print("both elements are equal")
    elif arr1[i]>=arr2[i]:
        print("arr1 have greater element")
    elif arr1[i]<=arr[2]:
        print("arr2 have gteater element")
index(4)

[10 22 30 40 65 34 54]
[11 22 23 44 56 34 54]
arr1 have greater element


In [13]:
#3.  Write a NumPy program to create an array of 10 zeros, 10 ones, 10    fives, 10 tens, 10 twentys and 10 fiftys.
arr1 = np.zeros(10)
arr2 = np.ones(10)
print(arr1)
print(arr2)
print(arr2*5)
print(arr2*10)
print(arr2*20)
print(arr2*50)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
[5. 5. 5. 5. 5. 5. 5. 5. 5. 5.]
[10. 10. 10. 10. 10. 10. 10. 10. 10. 10.]
[20. 20. 20. 20. 20. 20. 20. 20. 20. 20.]
[50. 50. 50. 50. 50. 50. 50. 50. 50. 50.]


In [14]:
#3.  Write a NumPy program to create an array of 10 zeros, 10 ones, 10    fives, 10 tens, 10 twentys and 10 fiftys.
arr1 = np.zeros(10)
arr2 = np.ones(10)
print(arr1,'\n',arr2,'\n',(arr2*5),'\n',(arr2*10),'\n',(arr2*15),'\n',(arr2*20))

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.] 
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.] 
 [5. 5. 5. 5. 5. 5. 5. 5. 5. 5.] 
 [10. 10. 10. 10. 10. 10. 10. 10. 10. 10.] 
 [15. 15. 15. 15. 15. 15. 15. 15. 15. 15.] 
 [20. 20. 20. 20. 20. 20. 20. 20. 20. 20.]


In [18]:
#4. Write a NumPy program to create an array of integers from 30 to 70.
arr = np.arange(30,71)
print(arr)

[30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50 51 52 53
 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70]


In [19]:
#5. Write a NumPy program to create an array of integers from 50 to 95.
arr = np.arange(50,96)
print(arr)

[50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71 72 73
 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95]


In [20]:
#6. Write a NumPy program to create an array of all even integers from 20 to 80..
arr = np.arange(21,81,2)
print(arr)

[20 22 24 26 28 30 32 34 36 38 40 42 44 46 48 50 52 54 56 58 60 62 64 66
 68 70 72 74 76 78 80]


In [21]:
#7. Write a NumPy program to create an array of all odd integers from 20 to 80.
arr = np.arange(21,81,2)
print(arr)

[21 23 25 27 29 31 33 35 37 39 41 43 45 47 49 51 53 55 57 59 61 63 65 67
 69 71 73 75 77 79]


In [25]:
#8. Write a NumPy program to generate an array of 15 random numbers from 10 to 40.
arr = np.random.randint(10,40,15)
print(arr)


[32 34 36 31 23 31 26 23 35 33 34 38 30 30 34]


In [26]:
#9. Write a NumPy program to generate an array of 10 random numbers from 30    to 50.
arr = np.random.randint(30,50,10)
print(arr)

[49 45 38 37 40 40 42 45 49 35]


In [27]:
#10. Write a NumPy program to generate an array of 20 random numbers from 50    to 90.
arr = np.random.randint(50,90,20)
print(arr)

[77 72 81 66 66 85 82 76 84 50 64 66 52 85 50 62 71 75 73 81]


In [28]:
#11. Create any two arrays & perform various mathematical operations.
    #i.e. Addition, Substraction, Multiplication, Divide.

arr1 = np.array([1,2,3,4,5,6,7,8,9])
arr2 = np.array([4,5,6,7,8,9,1,2,3])
print(arr1+arr2)
print(arr1-arr2)
print(arr1*arr2)
print(arr1/arr2)

[ 5  7  9 11 13 15  8 10 12]
[-3 -3 -3 -3 -3 -3  6  6  6]
[ 4 10 18 28 40 54  7 16 27]
[0.25       0.4        0.5        0.57142857 0.625      0.66666667
 7.         4.         3.        ]


In [30]:
#12. Write a NumPy program to create a 3x4 matrix filled with values from 10     to 21.
arr = np.arange(10,22).reshape(3,4)
print(arr)

[[10 11 12 13]
 [14 15 16 17]
 [18 19 20 21]]


In [39]:
#13. Write a NumPy program to create a 3x3 identity matrix, i.e. the diagonal     elements are 1, the rest are 0.
arr = np.array([1,0,0, 0, 1, 0, 0, 0, 1])
arr1 = arr.reshape(3,3)
print(arr1)

[[1 0 0]
 [0 1 0]
 [0 0 1]]


In [40]:
#14. Write a NumPy program to find the number of rows and columns in a given     matrix.
arr = np.eye(3)
print(arr)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [44]:
#15. Write a NumPy program to create a 5x5 zero matrix with elements on the     main diagonal equal to 1, 2, 3, 4, 5.
arr = np.diag([1,2,3,4,5])
print(arr)

[[1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]
 [0 0 0 0 5]]


In [50]:
#16. Write a NumPy program to create a 3x3x3 array filled with arbitrary     values.
arr = np.random.random((3,3,3))
print(arr)

[[[0.43100978 0.49446593 0.66127739]
  [0.98528388 0.96905137 0.33508747]
  [0.47327801 0.35494928 0.9241332 ]]

 [[0.41629332 0.52077726 0.1460091 ]
  [0.42961968 0.40743587 0.15683815]
  [0.1092566  0.1650378  0.86558244]]

 [[0.38241207 0.65081895 0.28236905]
  [0.21627239 0.73362339 0.34397689]
  [0.25369265 0.68396453 0.79461102]]]


In [51]:
#17. Write a NumPy program to create a 2x3x4 array filled with arbitrary values.
arr = np.random.random((2,3,4))
print(arr)

[[[0.19447206 0.58612206 0.05535319 0.42179278]
  [0.19747422 0.19510603 0.07387147 0.87022701]
  [0.65158487 0.68532073 0.57576026 0.81810223]]

 [[0.02716886 0.91683075 0.48083926 0.34378009]
  [0.77396079 0.40964466 0.06601741 0.5022    ]
  [0.95395383 0.17481224 0.22638681 0.29853302]]]


In [53]:
#18. Write a NumPy program to convert a list of numeric values into a one-    dimensional NumPy array.
arr = np.array([10,20,30,40,50,60,70,80,90])
print(arr)
print(type(arr))

[10 20 30 40 50 60 70 80 90]
<class 'numpy.ndarray'>


In [55]:
#19. Write a NumPy program to create a 3x3 matrix with values ranging from 2to 10.
arr = np.arange(2,11).reshape(3,3)
print(arr)

[[ 2  3  4]
 [ 5  6  7]
 [ 8  9 10]]


In [56]:
#20. Write a NumPy program to create an array with values ranging from 12 to 38.
arr = np.arange(12,38)
print(arr)

[12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35
 36 37]


In [64]:
#21. Write a NumPy program to reverse an array (the first element becomes the last)
arr = np.array([10,20,30,40,50])
print(arr[::-1])

[50 40 30 20 10]


In [68]:
#22. Write a NumPy program to convert an data type into to a floating type.
arr = np.array([11,22,33,44],dtype=np.float16)
print(arr)
print(f"the data type is {arr.dtype}")

[11. 22. 33. 44.]
the data type is float16


In [70]:
#23. Write a NumPy program to convert a list array.
l1 = [1,2,3,4,5,6,7,8,9]
print(f"the list is {l1}")
arr = np.array(l1)
print(f"list converted to array is {arr}")


the list is [1, 2, 3, 4, 5, 6, 7, 8, 9]
list converted to array is [1 2 3 4 5 6 7 8 9]


In [77]:
#24. Write a NumPy program to get the element-wise remainder of an array of division.
arr1 = np.array([10,20,30,45,65,32])
arr2 = np.array([2,5,4,6,3,8])
print(arr1%arr2)

[0 0 2 3 2 0]


In [76]:
#
#25. Write a NumPy program to get the element-wise remainder of an array of numbers from 20 to 50 which are divisible by 3.
arr = np.arange(20,50)
print(arr)
arr1 = (arr%3)
print(arr1)

[20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43
 44 45 46 47 48 49]
[2 0 1 2 0 1 2 0 1 2 0 1 2 0 1 2 0 1 2 0 1 2 0 1 2 0 1 2 0 1]
